    name: GitHub Pages Pushover Notification

    on:
      push:
        branches:
          - main # Or your GitHub Pages branch

    jobs:
      notify:
        runs-on: ubuntu-latest
        steps:
          - name: Send Pushover Notification
            env:
              PUSHOVER_USER_KEY: ${{ secrets.PUSHOVER_USER_KEY }}
              PUSHOVER_API_TOKEN: ${{ secrets.PUSHOVER_API_TOKEN }}
            run: |
              curl -s \
                -F "token=$PUSHOVER_API_TOKEN" \
                -F "user=$PUSHOVER_USER_KEY" \
                -F "message=GitHub Pages deployment successful for ${{ github.repository }}!" \
                -F "title=GitHub Pages Update" \
                https://api.pushover.net/1/messages.json
